{"cells":[{"cell_type":"markdown","metadata":{"id":"-KjSrZ1VCiEU"},"source":["![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)"]},{"cell_type":"markdown","source":["##[Clique aqui para acessar a documentação python: Erros e exceções](https://docs.python.org/pt-br/3/tutorial/errors.html)"],"metadata":{"id":"KU7m1C2LCi95"}},{"cell_type":"markdown","metadata":{"id":"f5PZUqkSCiEV"},"source":["# Exceções"]},{"cell_type":"markdown","metadata":{"id":"N2FPXEWTCiEV"},"source":["As exceções em Python são objetos que representam condições anormais que ocorrem durante a execução de um programa. Essas condições podem ser erros de sintaxe, erros de tempo de execução (como divisão por zero), tentativas de acesso a recursos indisponíveis, entre outros. As exceções fornecem uma maneira de lidar com esses erros de forma controlada e robusta, permitindo que o programa trate as situações inesperadas de maneira adequada."]},{"cell_type":"markdown","metadata":{"id":"zngE9q8pCiEW"},"source":["## Lançando Exceções"]},{"cell_type":"markdown","metadata":{"id":"kJK5JejPCiEW"},"source":["Em Python, exceções podem ser lançadas explicitamente usando a declaração `raise`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"SceCkbBkCiEX"},"outputs":[],"source":["def dividir(a, b):\n","    if b == 0:\n","        raise ValueError(\"Divisão por zero não é permitida\")\n","    return a / b"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"n96LF0C0CiEX","outputId":"3cb84d2a-4ded-49c3-de12-6940048add6a"},"outputs":[{"ename":"ValueError","evalue":"Divisão por zero não é permitida","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)","Cell \u001b[1;32mIn[7], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mdividir\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m)\u001b[49m\n","Cell \u001b[1;32mIn[6], line 3\u001b[0m, in \u001b[0;36mdividir\u001b[1;34m(a, b)\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdividir\u001b[39m(a, b):\n\u001b[0;32m      2\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m b \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[1;32m----> 3\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDivisão por zero não é permitida\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m      4\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m a \u001b[38;5;241m/\u001b[39m b\n","\u001b[1;31mValueError\u001b[0m: Divisão por zero não é permitida"]}],"source":["dividir(1, 0)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"gTi_3b5PCiEY","outputId":"2943601e-f059-4671-eb63-9939864d6902"},"outputs":[{"data":{"text/plain":["1.0"]},"execution_count":8,"metadata":{},"output_type":"execute_result"}],"source":["dividir(1,1)"]},{"cell_type":"markdown","metadata":{"id":"y6RbLNB6CiEY"},"source":["## Capturando e Tratando Exceções"]},{"cell_type":"markdown","metadata":{"id":"tNjb19y7CiEY"},"source":["Para lidar com exceções, podemos usar blocos `try` e `except`. O código dentro do bloco `try` é executado normalmente, e se uma exceção for lançada dentro deste bloco, o código dentro do bloco `except` correspondente é executado para tratar a exceção"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Bbb2MAncCiEZ"},"outputs":[],"source":["try:\n","    resultado = dividir(10, 0)\n","    print(\"Resultado da divisão:\", resultado)\n","except ValueError as ve:\n","    print(\"Erro:\", ve)\n",""]},{"cell_type":"markdown","metadata":{"id":"Zqmpo79qCiEZ"},"source":["## Bloco `finally`"]},{"cell_type":"markdown","metadata":{"id":"_FkptwElCiEZ"},"source":["Além do bloco `try` e `except`, podemos usar o bloco `finally`, que é executado sempre, independentemente de ocorrer uma exceção ou não. Por exemplo:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FkEKR7Y3CiEZ"},"outputs":[],"source":["try:\n","    resultado = dividir(10, 0)\n","    print(\"Resultado da divisão:\", resultado)\n","except ValueError as ve:\n","    print(\"Erro:\", ve)\n","finally:\n","    print(\"Fim da execução\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"AoPzQqWtCiEZ"},"outputs":[],"source":["try:\n","    resultado = dividir(10, 1)\n","    print(\"Resultado da divisão:\", resultado)\n","except ValueError as ve:\n","    print(\"Erro:\", ve)\n","finally:\n","    print(\"Fim da execução\")"]},{"cell_type":"markdown","metadata":{"id":"shzysEZMCiEa"},"source":["## Exceções Personalizadas"]},{"cell_type":"markdown","metadata":{"id":"-aNcBBnYCiEa"},"source":["Além das exceções embutidas, podemos definir nossas próprias exceções personalizadas criando classes que herdam da classe `Exception`. Isso permite que criemos exceções específicas para nossos programas e cenários"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"okpeMyN8CiEa"},"outputs":[],"source":["class SaldoInsuficienteError(Exception):\n","    \"\"\"Exceção levantada quando não há saldo suficiente.\"\"\"\n","    def __init__(self, saldo_atual, quantidade):\n","        super().__init__(f\"Saldo insuficiente. Saldo atual: {saldo_atual}, Quantidade necessária: {quantidade}\")\n","        self.saldo_atual = saldo_atual\n","        self.quantidade = quantidade"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Wlrhh9jkCiEa"},"outputs":[],"source":["def sacar(saldo, quantidade):\n","    if saldo < quantidade:\n","        raise SaldoInsuficienteError(saldo, quantidade)\n","    else:\n","        return saldo - quantidade"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"kID83pz8CiEa"},"outputs":[],"source":["saldo_atual = 100\n","quantidade_a_sacar = 150"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"WRuxwcMTCiEa","outputId":"8af3e887-e523-4b48-989a-7977c5c0916f"},"outputs":[{"name":"stdout","output_type":"stream","text":["Erro ao sacar: Saldo insuficiente. Saldo atual: 100, Quantidade necessária: 150\n"]}],"source":["try:\n","    novo_saldo = sacar(saldo_atual, quantidade_a_sacar)\n","    print(\"Saque realizado com sucesso. Novo saldo:\", novo_saldo)\n","except SaldoInsuficienteError as e:\n","    print(\"Erro ao sacar:\", e)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"CHOeMdGpCiEa"},"outputs":[],"source":["saldo_atual = 100\n","quantidade_a_sacar = 50"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ySZKLFqJCiEa","outputId":"6aa22c92-4a49-4f88-94a5-e8af3aa3d019"},"outputs":[{"name":"stdout","output_type":"stream","text":["Saque realizado com sucesso. Novo saldo: 50\n"]}],"source":["try:\n","    novo_saldo = sacar(saldo_atual, quantidade_a_sacar)\n","    print(\"Saque realizado com sucesso. Novo saldo:\", novo_saldo)\n","except SaldoInsuficienteError as e:\n","    print(\"Erro ao sacar:\", e)"]},{"cell_type":"markdown","metadata":{"id":"SBKuXtMXCiEa"},"source":["## Resumo"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rYarofe1CiEa"},"outputs":[],"source":["try:\n","    # Código que pode gerar uma exceção\n","except TipoDeExcecao:\n","    # Tratamento para a exceção\n","else:\n","    # Executado se nenhuma exceção for lançada\n","finally:\n","    # Sempre executado, independentemente de exceções"]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.12.4"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}